name: "Probabilistic-Numerics.org"
baseurl:


# changing this to custom will put links to pages at *.html rather than */
permalink: pretty

timezone: Europe/Berlin
description: A community website collecting research on algorithms that assign probability distributions to the unknown result of deterministic computations.

navigation:
- text: about/news
  url: /index.html
- text: blog
  url: /blog/index.html
- text: meetings
  url: /meetings/index.html
- text: research
  url: /research/index.html
- text: literature
  url: /literature/index.html

ftp_host: 'ud02.udmedia.de'
ftp_dir: '/html/numerics/'
ftp_passive: false
ftp_secure: true

# This makes the generator look at the date of each post (see "Every Jekyll
# Post has a Date"). Posts whose date is in the future will not be published.
# NB: This does not mean that, when you finally hit the date of a future post,
# the post will automatically appear. It only means that it will appear the
# next time you publish!
# https://github.com/bobgilmore/jekyll-blog/blob/master/_posts/2014-01-13-deferring-publication-in-jekyll.md
future: false

markdown: kramdown

scholar:
  style: apa
  repository: assets/pdf
  bibliography_template: bibliography
  replace_strings: true
  join_strings: true
  sort_by: year
  order: descending

